### PR TITLE
Fix disable required constraint for freetext and headline field

### LINKED ISSUE #379: Freetext fields have required constraints
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Bundle Version | 2.5.2
| Sulu Version | 2.5.10
| Browser Version | Firefox 125

#### Actual Behavior

When switching from a field with the "required" radio set, to a "freetext" field, the "required" radio disappears but the behaviour is still there and submitting the form trigger a required error on that field

#### Expected Behavior

No required constraint on freetext fields

#### Steps to Reproduce

1. Create a classic field and set the "required" on.
2. Switch this field to a "freetext" field
3. Save the form
4. Create a page including this form and try to send the form

#### Possible Solutions

Do not put any constraint on freetext fields

image

### PR DESCRIPTION
**Pull request by oprichnik**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #379
| Related issues/PRs | #379
| License | MIT

#### What's in this PR?

Checking field type before adding required constraint to avoid required constraint on free text fields.

EDIT: Maybe a easier way would be to reset all constraints for this type ?
image

### CODE REVIEW

File: Form/Type/DynamicFormType.php [hunk 1]
```diff
@@ -113,12 +114,14 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 $options['attr']['placeholder'] = $placeholder;
             }
 
+            $formFieldType = $this->typePool->get($field->getType());
+
             // required
-            if ($field->getRequired()) {
+            if (!$formFieldType instanceof FreeTextType && $field->getRequired()) {
```
Comment (alexander-schranz) [inline Form/Type/DynamicFormType.php]:
```suggestion
            if (
                !$formFieldType instanceof FreeTextType
                && !$formFieldType instanceof HeadlineType
                && $field->getRequired()
            ) {
```

File: Form/Type/DynamicFormType.php [hunk 2]
```diff
@@ -13,6 +13,7 @@
 
 use Sulu\Bundle\FormBundle\Dynamic\Checksum;
 use Sulu\Bundle\FormBundle\Dynamic\FormFieldTypePool;
+use Sulu\Bundle\FormBundle\Dynamic\Types\FreeTextType;
```
Comment (alexander-schranz) [inline Form/Type/DynamicFormType.php:16]:
```suggestion
use Sulu\Bundle\FormBundle\Dynamic\Types\FreeTextType;
use Sulu\Bundle\FormBundle\Dynamic\Types\HeadlineType;
```

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@oprichnik thank you!
